### ISSUE TITLE
ship_order_item response

### ISSUE THREAD

**Issue by jnkg9** [dreambits/python-bol-api#42]
Hi @karan-dreambits , @bharti-dreambits, 

First of all, thanks for all the great work you’re sharing. It is very useful already.

I have a question regarding using `ship_order_item`.
Either I'm not using it correctly or there is an issue with it.

When executing:
`response = api.orders.ship_order_item(order_id, shipment_reference=shipmentReferenceString, transporter_code="TNT", track_and_trace= ””)`
(Here, order_id is an open order id string of a real order, and shipmentReferenceString just some random string.)
It does not actually confirm the order on [bol.com](http://bol.com/). The response also does not give an error, but gives 202.

Am I doing something wrong here, should `ship_order_item` be used differently? If so, can you show an example (or add it to the documentation) of how you use it?

Looking forward to hearing from you!

Thanks in advance,

Cheers,

Jan

**Comment by karan-dreambits** [comment]
Hi @jankoning9 , 

We are glad to hear that the library has been useful. 

Regarding your question, I would need to check once through the commit history to find if and when things got changed but due to the structure of Bol.com api the `ship_order_item` function expects `order_item_id` as the first argument as you can see on their [redoc](https://api.bol.com/retailer/public/redoc/v7/retailer.html#operation/ship-order-item)

While there is no clear documentation on the library but if you look at the names of argument in the [function](https://github.com/dreambits/python-bol-api/blob/master/bol/retailer/api.py#L66) then the same is reflected. 

So can you try changing your code from 

`response = api.orders.ship_order_item(order_id, shipment_reference=shipmentReferenceString, transporter_code="TNT", track_and_trace= ””)`

To 

`response = api.orders.ship_order_item(order_item_id, shipment_reference=shipmentReferenceString, transporter_code="TNT", track_and_trace= ””)`

and see if that works ?

**Comment by jankoning9** [comment]
Thanks for your quick reply @karan-dreambits !

Changing `order_id ` to `order_item_id ` unfortunately does not change anything, as it is merely how I called the variable containing the string of the order id in my script. 

After calling, the following function from the api.py is being used, If I'm correct:
```
def ship_order_item(
        self,
        order_item_id,
        shipment_reference,
        shipping_label_id=None,
        transporter_code=None,
        track_and_trace=None,
    ):
        payload = {}
        orderItems = [
            {
                "orderItemId": order_item_id
            }
        ]
        payload["orderItems"] = orderItems
        payload["shipmentReference"] = shipment_reference
        # if shipping_label_id:
        #     payload["shippingLabelId"] = shipping_label_id
        # else:
        if transporter_code:
            payload.setdefault("transport", {})[
                "transporterCode"
            ] = transporter_code
        if track_and_trace:
            payload.setdefault("transport", {})[
                "trackAndTrace"
            ] = track_and_trace
        resp = self.request(
            "PUT", path="shipment", json=payload
        )
        print(payload)
        # return resp #  added as test
        return ProcessStatus.parse(self.api, resp.text)
```
Here it is indeed as you say, and order_item_id is being used first argument, right?
